application:
  version: "1"

orion:
  serverUrl: "http://set.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

jubatus:
  host: "localhost"
  basePort: 9000

---
spring:
  profiles: develop
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
server.port: 8080
application:
  baseUrl: "http://150.140.5.27:8080/"
  annotationUrl: "https://annotations.organicity.eu/"
  env: dev
orion:
  serverUrl: "http://dev.server.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"
---
spring:
  profiles: production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver
application:
  baseUrl: "http://150.140.5.27:8080/"
  annotationUrl: "https://annotations.organicity.eu/"
  env: production
orion:
  serverUrl: "http://dev.server.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

---
spring:
  profiles: local
  datasource.url: jdbc:hsqldb:file:hsqldb/hsqldb
  jpa.hibernate.ddl-auto: update

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
  show_sql: false
server.port: 8080
application:
  baseUrl: "http://150.140.5.32:8080/"
  annotationUrl: "http://146.169.46.162:8084/"
  env: dev

---
spring:
  profiles: test

application:
  baseUrl: "http://jamaica.organicity.eu/"
  annotationUrl: "https://annotations.organicity.eu/"
  env: dev