application:
  version: "1"

orion:
  serverUrl: "http://set.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

jubatus:
  host: "localhost"
  basePort: 9000

spring:
  thymeleaf:
    enabled: true
    cache: false

log.path: "logs/"

---
spring:
  profiles: develop
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: none
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/oc_jamaica_${user.name}
    test-on-borrow: true
    validation-query: "select 1"
server.port: 8080
application:
  baseUrl: "http://jamaica.organicity.eu/"
  annotationUrl: "https://annotations.organicity.eu/"
  discoveryUrl: "https://discovery.organicity.eu/v0/"
  env: dev
  keycloak.file: "keycloak.json"
orion:
  serverUrl: "http://orion.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"
---
spring:
  profiles: production
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    generate-ddl: false
    hibernate.ddl-auto: none
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb_jamaica:3306/jamaica
    test-on-borrow: true
    validation-query: "select 1"
log.path: "logs/"
application:
  baseUrl: "http://jamaica.organicity.eu/"
  annotationUrl: "https://annotations.organicity.eu/"
  discoveryUrl: "https://discovery.organicity.eu/v0/"
  env: production
  keycloak.file: "/keycloak.json"
orion:
  serverUrl: "http://orion.organicity.eu:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

---
spring:
  profiles: local
  datasource.url: jdbc:hsqldb:file:hsqldb/hsqldb
  jpa.hibernate.ddl-auto: none

hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
  show_sql: false
server.port: 8080
application:
  baseUrl: "http://150.140.5.32:8080/"
  annotationUrl: "http://146.169.46.162:8084/"
  env: dev

---
spring:
  profiles: test

application:
  baseUrl: "http://jamaica.organicity.eu/"
  annotationUrl: "https://annotations.organicity.eu/"
  env: dev