application:
  version: "1"
  baseUrl: "http://150.140.5.32:8080/"

orion:
  serverUrl: "http://195.220.224.30:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

jubatus:
  host: "localhost"
  basePort: 9000

---
spring:
  profiles: develop
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver

---
spring:
  profiles: production
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate.ddl-auto: update
  datasource:
    driverClassName: org.postgresql.Driver

---
spring:
  profiles: local
  datasource.url: jdbc:hsqldb:file:hsqldb
  jpa.hibernate.ddl-auto: update

# hibernate.X
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
  show_sql: false
  hbm2ddl.auto: update
