application:
  version: "1"
  baseUrl: "http://150.140.5.32:8080/"
# DataSource
spring.datasource.url: jdbc:hsqldb:file:hsqldb
spring.jpa.hibernate.ddl-auto: update
# hibernate.X
hibernate.dialect: org.hibernate.dialect.HSQLDialect
hibernate.show_sql: false
hibernate.hbm2ddl.auto: update

orion:
  serverUrl: "http://195.220.224.30:1026/"
  token: ""
  service: "organicity"
  servicePath: "/"

jubatus:
  host: "localhost"
  basePort: 9000